# fly.toml app configuration file generated for resume-fercandia on 2024-09-09T20:36:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-fercandia'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
